#!/usr/bin/env python3
"""
make_images.py — Generate Preview PNG Images for Lochraster Boards
===================================================================
Date:    2026-03-26
Author:  Nils Achermann
Note:    Code generated by and cross-checked with an AI system using dedicated
         code-review agents.

Creates a side-by-side preview PNG for each board: front side (left) and back
side mirrored (right), plus an overview grid combining all 12 variants.

Pipeline per board:
  1. Export front and back SVGs via kicad-cli (--exclude-drawing-sheet)
  2. Inject a JLCPCB-violet (#2d1b4e) rounded-rect background into each SVG
  3. Rasterise SVGs to PNG via cairosvg
  4. Combine front + back into a single image with Pillow

Output goes to Projekt/images/.  Requires kicad-cli, cairosvg, and Pillow.

Usage:
  python make_images.py
"""
import os, re, subprocess, sys, glob

KICAD_CLI = r"C:\Program Files\KiCad\9.0\bin\kicad-cli.exe"
LAYERS_F = "F.Cu,F.SilkS,Edge.Cuts"
LAYERS_B = "B.Cu,B.SilkS,Edge.Cuts"
JLCPCB_VIOLET = "#2d1b4e"
SIDE_WIDTH = 400              # pixels wide per side
GAP = 10                      # pixel gap between front and back

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(SCRIPT_DIR, "Projekt", "images")
TEMP = os.environ.get("TEMP", "/tmp")


def export_svg(pcb_path, svg_path, layers, mirror=False):
    """Export PCB to single-file SVG via kicad-cli."""
    cmd = [
        KICAD_CLI, "pcb", "export", "svg",
        "--layers", layers,
        "--mode-single",
        "--exclude-drawing-sheet",
        "--page-size-mode", "2",
        "--drill-shape-opt", "2",
        "-o", svg_path,
    ]
    if mirror:
        cmd.append("--mirror")
    cmd.append(pcb_path)
    subprocess.run(cmd, check=True, capture_output=True)


def inject_board_bg(svg_path, board_w_mm, board_h_mm, corner_r=4.0):
    """Insert a violet rounded-rect board background as the first visible element."""
    svg = open(svg_path, encoding="utf-8").read()

    vb = re.search(r'viewBox="([\d.]+)\s+([\d.]+)\s+([\d.]+)\s+([\d.]+)"', svg)
    if not vb:
        return
    vb_x, vb_y, vb_w, vb_h = float(vb.group(1)), float(vb.group(2)), float(vb.group(3)), float(vb.group(4))

    margin = (vb_w - board_w_mm) / 2
    bx = vb_x + margin
    by = vb_y + (vb_h - board_h_mm) / 2

    bg_rect = (
        f'<rect x="{bx:.4f}" y="{by:.4f}" '
        f'width="{board_w_mm:.4f}" height="{board_h_mm:.4f}" '
        f'rx="{corner_r}" ry="{corner_r}" '
        f'fill="{JLCPCB_VIOLET}" />\n'
    )

    insertion = svg.find("</g>")
    if insertion < 0:
        return
    insertion += len("</g>") + 1
    svg = svg[:insertion] + bg_rect + svg[insertion:]

    open(svg_path, "w", encoding="utf-8").write(svg)


def svg_to_png(svg_path, png_path, width):
    """Convert SVG to PNG using cairosvg."""
    import cairosvg
    cairosvg.svg2png(url=svg_path, write_to=png_path, output_width=width)


def main():
    from PIL import Image

    os.makedirs(OUT_DIR, exist_ok=True)
    pcb_files = sorted(glob.glob(os.path.join(SCRIPT_DIR, "proto_*.kicad_pcb")))

    if not pcb_files:
        print("No proto_*.kicad_pcb files found.")
        return 1

    for pcb_path in pcb_files:
        fname = os.path.basename(pcb_path)
        m = re.match(r'proto_(\d+)x(\d+)_(\w+)\.kicad_pcb$', fname)
        if not m:
            continue
        bw, bh = int(m.group(1)), int(m.group(2))
        name = fname.replace(".kicad_pcb", "")

        svg_f = os.path.join(TEMP, f"{name}_F.svg")
        svg_b = os.path.join(TEMP, f"{name}_B.svg")
        png_f = os.path.join(TEMP, f"{name}_F.png")
        png_b = os.path.join(TEMP, f"{name}_B.png")
        png_out = os.path.join(OUT_DIR, f"{name}.png")

        print(f"  {fname} -> {name}.png ...", end=" ", flush=True)

        # Export front and back SVGs
        export_svg(pcb_path, svg_f, LAYERS_F)
        export_svg(pcb_path, svg_b, LAYERS_B, mirror=True)

        # Inject violet background
        inject_board_bg(svg_f, bw, bh)
        inject_board_bg(svg_b, bw, bh)

        # Convert to PNG
        svg_to_png(svg_f, png_f, SIDE_WIDTH)
        svg_to_png(svg_b, png_b, SIDE_WIDTH)

        # Combine side by side: F (left) | B mirrored (right)
        img_f = Image.open(png_f)
        img_b = Image.open(png_b)
        # Match heights
        max_h = max(img_f.height, img_b.height)
        total_w = img_f.width + GAP + img_b.width
        combined = Image.new("RGB", (total_w, max_h), (45, 27, 78))
        combined.paste(img_f, (0, (max_h - img_f.height) // 2))
        combined.paste(img_b, (img_f.width + GAP, (max_h - img_b.height) // 2))
        combined.save(png_out)

        print("OK")

    # Overview grid
    print("\n  Generating overview grid ...", end=" ", flush=True)
    try:
        sizes = [(50, 70), (70, 100), (100, 160)]
        types = ["unconnected", "stripboard", "group_3", "breadboard"]
        thumb_w = SIDE_WIDTH * 2 + GAP
        cols = len(types)
        rows = len(sizes)

        imgs = {}
        max_h_per_row = [0] * rows
        for ri, (sw, sh) in enumerate(sizes):
            for ci, tp in enumerate(types):
                p = os.path.join(OUT_DIR, f"proto_{sw}x{sh}_{tp}.png")
                if os.path.exists(p):
                    img = Image.open(p)
                    # Scale to thumb_w
                    scale = thumb_w / img.width
                    img = img.resize((thumb_w, int(img.height * scale)), Image.LANCZOS)
                    imgs[(ri, ci)] = img
                    if img.height > max_h_per_row[ri]:
                        max_h_per_row[ri] = img.height

        total_w = thumb_w * cols
        total_h = sum(max_h_per_row)
        overview = Image.new("RGB", (total_w, total_h), (45, 27, 78))

        y_off = 0
        for ri in range(rows):
            for ci in range(cols):
                img = imgs.get((ri, ci))
                if img:
                    x = ci * thumb_w + (thumb_w - img.width) // 2
                    y = y_off + (max_h_per_row[ri] - img.height) // 2
                    overview.paste(img, (x, y))
            y_off += max_h_per_row[ri]

        overview.save(os.path.join(OUT_DIR, "overview_all_boards.png"))
        print("OK")
    except Exception as e:
        print(f"SKIP ({e})")

    print("\nDone!")
    return 0


if __name__ == "__main__":
    sys.exit(main())
